DROP TABLE IF EXISTS records;
DROP TABLE IF EXISTS foreverYoung;
DROP TABLE IF EXISTS newKnowledge;
DROP TABLE IF EXISTS nucare;
DROP TABLE IF EXISTS businesses;
DROP TABLE IF EXISTS nucareCOA;

CREATE TABLE businesses(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL
);

CREATE TABLE newKnowledge(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    descr TEXT NOT NULL,
    account TEXT NOT NULL
);

CREATE TABLE foreverYoung(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    descr	TEXT NOT NULL,
    account	TEXT NOT NULL
);

CREATE TABLE nucare(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    descr	TEXT NOT NULL,
    account	TEXT NOT NULL
);

CREATE TABLE nucareCOA(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    descr	TEXT NOT NULL
)